# -*- coding: utf-8 -*-
"""stacking-main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mij6-4NMT6FPIpo0FWGMUCn187o68dyM
"""

import stacking_utils as utils

def main(df, WH, pred_start, pred_end,val_dates,important_date='No'):

    future = utils.create_prediction_range(pred_start, pred_end)
    df = utils.select_wh(df, WH)
  
    result = utils.stack_model(df, future, WH)
    if important_date == 'Yes':
        result = result[result['ds'].isin(val_dates)]
    result = utils.final_formatting(result)  
    return result
