# -*- coding: utf-8 -*-
"""stacking-main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mij6-4NMT6FPIpo0FWGMUCn187o68dyM
"""

import stacking_utils as utils

def main(df, WH, pred_date, model_name_list):

  train_start_date = {'ALL BSD':'2020-11','ALL LEGOK 10K':'2020-10','ALL LEGOK B6, A7':'2021-01','ALL SURABAYA':'2021-09','ALL FF':'2021-11'}
  future = utils.create_prediction_range(df, pred_date)
  df = utils.select_wh(df, WH, train_start_date, pred_date)

  result = utils.stack_model(df, future, WH, model_name_list)
  
  return result
